# Generated by Django 5.2.8 on 2025-11-27 19:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_created', models.DateTimeField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Guide'), ('admin', 'Admin')], default='tourist', max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'wilayas',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_app.user')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_app.user')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tourist',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_app.user')),
                ('biography', models.TextField(blank=True, null=True)),
                ('offering_spoken_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('phone', models.CharField(max_length=13)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('full_day_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('half_day_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_hour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certifications_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('custom_request_markup', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_guides', to='backend_app.admin')),
            ],
            options={
                'db_table': 'guide',
            },
        ),
        migrations.CreateModel(
            name='CoverageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed', models.CharField(blank=True, max_length=100, null=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_zones', to='backend_app.wilaya')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_zones', to='backend_app.guide')),
            ],
            options={
                'db_table': 'coveragezone',
                'unique_together': {('guide', 'wilaya')},
            },
        ),
    ]
