# Generated by Django 5.2.8 on 2025-11-29 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(help_text='Scheduled date of the tour')),
                ('itinerary', models.TextField(help_text='Suggested itinerary and route')),
                ('highlights', models.TextField(help_text='Key attractions')),
                ('whats_included', models.TextField()),
                ('whats_excluded', models.TextField()),
                ('estimated_duration', models.DecimalField(decimal_places=2, help_text='Duration in hours (e.g., 3.5)', max_digits=4)),
                ('calculated_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('starting_point', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('available_places', models.IntegerField(help_text='Number of available places for this tour', validators=[django.core.validators.MinValueValidator(1)])),
                ('photo_urls', models.JSONField(default=list)),
                ('cover_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='backend_app.guide')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='backend_app.wilaya')),
            ],
            options={
                'db_table': 'tour',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend_app.guide')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend_app.tourist')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend_app.tour')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='accepted', max_length=20)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='backend_app.guide')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='backend_app.tour')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='backend_app.tourist')),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['-created_at'],
            },
        ),
    ]
