# Generated by Django 5.2.8 on 2025-11-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_tour_review_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='guide',
        ),
    ]
