# Generated by Django 5.2.9 on 2025-12-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('departure_location', models.CharField(blank=True, max_length=255)),
                ('tourist_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_requests', to='backend_app.guide')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_requests', to='backend_app.tourist')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.wilaya')),
            ],
            options={
                'db_table': 'personalized_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
