# Generated by Django 5.2.8 on 2025-12-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_reservation_final_price_reservation_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled time of the tour', null=True),
        ),
    ]
