# Generated by Django 5.2.8 on 2025-12-24 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_created', models.DateTimeField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Guide'), ('admin', 'Admin')], default='tourist', max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'wilayas',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_app.user')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_app.user')),
                ('biography', models.TextField(blank=True, null=True)),
                ('offering_spoken_languages', models.JSONField(default=list)),
                ('phone', models.CharField(max_length=13)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('full_day_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('half_day_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_hour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certifications_files', models.JSONField(blank=True, default=list)),
                ('custom_request_markup', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_guides', to='backend_app.admin')),
            ],
            options={
                'db_table': 'guide',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_app.user')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tourist',
            },
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'latitude', 'longitude'], name='backend_app_date_2b4fb3_idx')],
                'unique_together': {('date', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(help_text='Scheduled date of the tour')),
                ('itinerary', models.TextField(help_text='Suggested itinerary and route')),
                ('highlights', models.TextField(help_text='Key attractions (one per line)')),
                ('whats_included', models.TextField(help_text="What's included (one per line)")),
                ('whats_excluded', models.TextField()),
                ('estimated_duration', models.DecimalField(decimal_places=2, help_text='Duration in hours (e.g., 3.5)', max_digits=4)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Scheduled time of the tour', null=True)),
                ('calculated_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('starting_point', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_places', models.IntegerField(default=10, help_text='Maximum number of places for this tour (set by guide)', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_places', models.IntegerField(default=10, help_text='Number of available places remaining for this tour', validators=[django.core.validators.MinValueValidator(0)])),
                ('photo_urls', models.JSONField(default=list)),
                ('cover_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='backend_app.wilaya')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='backend_app.guide')),
            ],
            options={
                'db_table': 'tour',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend_app.tour')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend_app.tourist')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='accepted', max_length=20)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Scheduled time of the tour', null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='backend_app.tour')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='backend_app.guide')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='backend_app.tourist')),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed', models.CharField(blank=True, max_length=100, null=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_zones', to='backend_app.wilaya')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_zones', to='backend_app.guide')),
            ],
            options={
                'db_table': 'coveragezone',
                'unique_together': {('guide', 'wilaya')},
            },
        ),
    ]
