# Generated by Django 5.2.8 on 2025-11-22 19:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'wilayas',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_app.user')),
            ],
            options={
                'db_table': 'admin',
            },
            bases=('backend_app.user',),
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_app.user')),
                ('biography', models.TextField(blank=True, null=True)),
                ('offering_spoken_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('phone', models.CharField(max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('fullday_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('half_day_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_hour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certifications_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('customrequestmarkup', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'guide',
            },
            bases=('backend_app.user',),
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_app.user')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tourist',
            },
            bases=('backend_app.user',),
        ),
        migrations.CreateModel(
            name='CoverageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed', models.CharField(blank=True, max_length=100, null=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_zones', to='backend_app.wilaya')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_zones', to='backend_app.guide')),
            ],
            options={
                'db_table': 'coveragezone',
                'unique_together': {('guide', 'wilaya')},
            },
        ),
    ]
