# Generated by Django 5.2.8 on 2025-11-22 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='fullday_price',
            new_name='full_day_price',
        ),
        migrations.AlterField(
            model_name='guide',
            name='offering_spoken_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
