# Generated by Django 5.2.8 on 2025-11-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_rename_fullday_price_guide_full_day_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='customrequestmarkup',
            new_name='custom_request_markup',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
