# Generated by Django 5.2.8 on 2025-12-02 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_remove_review_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Scheduled date of the tour'),
        ),
    ]
