# Generated by Django 5.2.8 on 2025-12-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_tour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tourist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='backend_app.tourist'),
        ),
    ]
