# Generated by Django 5.2.8 on 2025-12-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_reservation_tourist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
    ]
