# Generated by Django 5.2.8 on 2025-12-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_reservation_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled time of the tour', null=True),
        ),
    ]
