# Generated by Django 5.2.8 on 2025-12-03 00:15

import django.core.validators
from django.db import migrations, models


def set_max_places_for_existing_tours(apps, schema_editor):
    """
    Set max_places for existing tours based on their current available_places.
    For existing tours, we assume max_places should be at least equal to available_places.
    We'll set it to max(available_places, 10) to ensure a reasonable minimum.
    """
    Tour = apps.get_model('backend_app', 'Tour')
    for tour in Tour.objects.all():
        # Set max_places to be at least as large as available_places
        # Use max(available_places, 10) to ensure a reasonable minimum
        tour.max_places = max(tour.available_places, 10) if tour.available_places else 10
        tour.save(update_fields=['max_places'])


def reverse_set_max_places(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_tour_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='max_places',
            field=models.IntegerField(default=10, help_text='Maximum number of places for this tour (set by guide)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='available_places',
            field=models.IntegerField(default=10, help_text='Number of available places remaining for this tour', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(set_max_places_for_existing_tours, reverse_set_max_places),
    ]
